In [1]:
import numpy as np

In [2]:
n = 4 #number of iterations
true_val = 72

In [3]:
estimate = np.zeros((n+1,1)).reshape(n+1,1)
estimate[0] = 68
estimate

array([[68.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [4]:
estimate_error = np.zeros((n+1,1)).reshape(n+1,1)
estimate_error[0] = 2
estimate_error

array([[2.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
measured = np.array([0, 75, 71, 70, 74]).reshape(n+1,1)
measured_error = np.array([0, 4, 4, 4, 4]).reshape(n+1,1)


In [6]:
kalman_gain = np.zeros((n+1,1)).reshape(n+1,1)

In [7]:
for i in range(1,n+1):
    
    
    kalman_gain[i] = (estimate_error[i-1])/(estimate_error[i-1] + measured_error[i])
    
    estimate[i] = estimate[i-1] + ( kalman_gain[i] * (measured[i] - estimate[i-1]) )
    
    estimate_error[i] = (1 - kalman_gain[i]) * estimate_error[i-1]
    
    

In [8]:
estimate

array([[68.        ],
       [70.33333333],
       [70.5       ],
       [70.4       ],
       [71.        ]])

In [9]:
kalman_gain

array([[0.        ],
       [0.33333333],
       [0.25      ],
       [0.2       ],
       [0.16666667]])

In [10]:
estimate_error

array([[2.        ],
       [1.33333333],
       [1.        ],
       [0.8       ],
       [0.66666667]])